# Generated by Django 4.2.20 on 2025-03-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
