# Generated by Django 4.2.20 on 2025-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0002_remove_user_date_joined_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
