# Generated by Django 4.2.20 on 2025-03-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0003_deputy_description_alter_user_patronymic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='priemka.appointmentstatus'),
        ),
    ]
