# Generated by Django 4.2.20 on 2025-03-24 19:39

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0005_appointment_appointment'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='appointment',
            name='appointment',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='appointment', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE "priemka_appointment" SET is_archived = True WHERE "id" = OLD."id"; RETURN NULL;', hash='a2d42d4ef77929f941b89064b6f89558118153a8', operation='DELETE', pgid='pgtrigger_appointment_114ae', table='priemka_appointment', when='BEFORE')),
        ),
    ]
