# Generated by Django 4.2.20 on 2025-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0006_remove_appointment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputyschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputyschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
