# Generated by Django 4.2.20 on 2025-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0007_deputyschedule_break_end_deputyschedule_break_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')]),
        ),
    ]
