# Generated by Django 4.2.20 on 2025-03-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0008_alter_deputyschedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputyschedule',
            name='max_appointments_per_day',
        ),
    ]
