# Generated by Django 4.2.20 on 2025-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0009_remove_deputyschedule_max_appointments_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
