# Generated by Django 4.2.20 on 2025-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0010_alter_appointment_description_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='appointment',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_time',
            field=models.TimeField(default='08:30', verbose_name='appointed time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointed_date',
            field=models.DateField(verbose_name='appointed date'),
        ),
        migrations.AlterIndexTogether(
            name='appointment',
            index_together={('deputy', 'user', 'title', 'appointment_theme', 'appointed_date', 'appointed_time')},
        ),
    ]
