# Generated by Django 4.2.20 on 2025-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0012_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления по email'),
        ),
    ]
