# Generated by Django 4.2.20 on 2025-03-30 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0013_user_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_update_reason',
            field=models.TextField(blank=True, verbose_name='Причина изменения'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил запись'),
        ),
    ]
