# Generated by Django 4.2.20 on 2025-04-05 16:23

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0016_deputy_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Статус решения',
                'verbose_name_plural': 'Статусы решений',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_text', models.TextField(verbose_name='Текст решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_final', models.BooleanField(default=False, verbose_name='Решение окончательное')),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='priemka.appointment', verbose_name='Запись на прием')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='priemka.deputy', verbose_name='Депутат')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='priemka.decisionstatus', verbose_name='Статус решения')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'index_together': {('appointment', 'deputy', 'created_at')},
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='decision',
            trigger=pgtrigger.compiler.Trigger(name='appointment', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE "priemka_decision" SET is_archived = True WHERE "id" = OLD."id"; RETURN NULL;', hash='d0ebea294992c1c2d128eb96066b6af6b59e60d6', operation='DELETE', pgid='pgtrigger_appointment_f44f4', table='priemka_decision', when='BEFORE')),
        ),
    ]
