# Generated by Django 4.2.20 on 2025-04-06 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priemka', '0018_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_decision', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил запись'),
        ),
    ]
