version: '3.9'

services:
  web:
    container_name: web
    hostname: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    environment:
      DEBUG: 1
      DATABASE_URL: postgres://memberremember:1504@db:5432/sdmopriemka
      TZ: "Europe/Moscow"
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: memberremember
      POSTGRES_PASSWORD: 1504
      POSTGRES_DB: sdmopriemka

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1504
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: